version: '3.8'
nginx:
    build:
      context: ./
      dockerfile: ./.docker-compose/nginx/Dockerfile
      args:
        user: www
        uid: 1000
    image: goodfood-nginx
    container_name: my-app
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - ./:/var/www